### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by etoledo1** [jdoggett1/TourTheBMWZentrum#2]
First of all, I really liked the idea behind your website and I believe it is very creative. I have a couple technical suggestions but overall the coding looks great, so they are just very small recommendations:

Index
In this page you did not close the last div on line 55.
```
<div class="center">
      <button
        class="tourbtn"
        onclick="window.location.href='https://www.tourbmwzentrum.live/m3gt.html';"
      >
        Continue Tour ➟
      </button>
```
 
Pfcntr
For the <iframe> tag, I noticed that this is not really used anymore. You can read more here: https://chimney.io/iframes-are-killing-your-website/ 
`   <iframe width="560" height="315" src="https://www.youtube.com/embed/aGkQl-Nl-YM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`
 
Form
The label for attribute must contain the input id value on line 73.
```
<label id="cntry" for="country-choice">Country:</label>
          <input
          type="text"
          name="country"
          id="country"
          placeholder="Enter your country here"
          />
```
 
Regarding content, I believe it might be a good idea to add some text in your index page so that the user knows what to expect. Also, at the end of every page there is a Compare (Select) part, and I did not really understand it. I believe you should probably add some text explaining it.

**Comment by jdoggett1** [comment]
Thank you for your peer review! Your feedback has been very helpful for improving my site!
